name: peregrine_flutter
description: A cross-platform fitness app with AI coaching and health tracking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  
  # Health Data
  health: ^8.1.0
  health_kit: ^0.0.6
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # AI & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.0.1
  
  # Background Tasks
  workmanager: ^0.5.2
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Date & Time
  table_calendar: ^3.0.9
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^2.6.1
  build_runner: ^2.5.4
  freezed: ^3.0.0-0.0.dev
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 